language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
install:
  - npm install aglio
script:
  - docker build -t dojot/flowbroker .
  - docker build -t tests/flowbroker -f ./tests/Dockerfile .
  - docker-compose -f tests/docker-compose.yml up -d kafka rabbitmq data-broker mongodb auth flowbroker
  - docker-compose -f ./tests/docker-compose.yml run --rm tester

after_success:
  - travis/publish.sh
  - travis/deploy-gh-pages.sh
