language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
install:
  - npm install aglio
script:
  - docker build -t flowbroker-tests . -f ./tests/Dockerfile
  - docker-compose -f tests/docker-compose.yml up -d kafka rabbitmq data-broker mongodb auth
  - docker-compose -f ./tests/docker-compose.yml run flowbroker
  - docker build -t dojot/flowbroker .

after_success:
  - travis/publish.sh
  - travis/deploy-gh-pages.sh
